# Generated by Django 4.0 on 2021-12-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('account_number', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('annual_revenue', models.CharField(blank=True, max_length=32, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesForceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(max_length=64, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=128, null=True)),
                ('lastname', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('account_id', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('mailing_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesForceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('firstname', models.CharField(blank=True, max_length=128, null=True)),
                ('lastname', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
