# Generated by Django 3.2.9 on 2021-12-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforcecontact',
            name='account_id',
        ),
        migrations.AddField(
            model_name='salesforcecontact',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesforce.salesforceaccount'),
        ),
    ]
